version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Nancy.Template.WebService.csproj -v quiet
build_script:
  - cmd: dotnet publish ./src/Nancy.Template.WebService.csproj -v minimal
test_script:
  - cmd: dotnet test ./tests/Nancy.Template.WebService.Tests.csproj  -v minimal 
skip_commits:
  files:
    - '**/*.md'
